# Generated by Django 4.2.18 on 2025-02-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BinaryField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
