# Generated by Django 4.2.18 on 2025-02-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_address',
            field=models.CharField(default='e@gmail.com', max_length=600),
        ),
    ]
