# Generated by Django 4.2.18 on 2025-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_users_dob_users_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=300)),
                ('device_brand', models.CharField(max_length=300)),
                ('device_type', models.CharField(choices=[('laptop', 'LAPTOP'), ('desktop', 'DESKTOP'), ('projector', 'PROJECTOR'), ('TV', 'TV'), ('Other', 'OTHER')], max_length=100)),
                ('device_os', models.CharField(choices=[('windows10', 'WIN10'), ('windows11', 'WIN11'), ('ChromeOS', 'CHROMEOS'), ('Linux', 'LINUX'), ('macOS', 'MACOS'), ('other', 'OTHER')], max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
