# Generated by Django 4.2.18 on 2025-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_devices_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='room',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
